name: Baking factory

on:
  workflow_call:
    inputs:
      path:
        required: true
        type: string
      target:
        required: true
        type: string # release or nightly
      commit:
        required: false
        type: string
      dockerfile:
        required: false
        type: string
        default: Dockerfile
      runs-on:
        required: false
        type: string
        default: ubuntu-latest

jobs:
  build:
    permissions:
      contents: read
      packages: write
    runs-on: ${{ inputs.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: vafanassieff
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Print Bake file
        env:
          COMMIT: ${{ inputs.commit }}
          IMAGE_PATH: ${{ inputs.path }}
        run: |
          docker buildx bake \
          --file ${{ inputs.path }}/image.hcl \
          --file docker-bake.hcl \
          --print ${{ inputs.target }}

      - name: Run Docker buildx without cache
        if: ${{ github.event.inputs.force }}
        env:
          COMMIT: ${{ inputs.commit }}
          IMAGE_PATH: ${{ inputs.path }}
          DOCKERFILE: ${{ inputs.dockerfile }}
        run: |
          docker buildx bake \
          --set *.output="type=registry" \
          --file ${{ inputs.path }}/image.hcl \
          --file docker-bake.hcl \
           ${{ inputs.target }}

      - name: Run Docker buildx against latest
        if: ${{ !github.event.inputs.force }}
        env:
          COMMIT: ${{ inputs.commit }}
          IMAGE_PATH: ${{ inputs.path }}
          DOCKERFILE: ${{ inputs.dockerfile }}
        run: |
          docker buildx bake \
          --set *.output="type=registry" \
          --file ${{ inputs.path }}/image.hcl \
          --file docker-bake.hcl \
           ${{ inputs.target }}
