name: Baking factory

on:
  workflow_call:
    inputs:
      path:
        required: true
        type: string
      target:
        required: true
        type: string # release or nightly
      commit:
        required: false
        type: string
      dockerfile:
        required: false
        type: string
        default: Dockerfile
      runs-on:
        required: false
        type: string
        default: ubuntu-latest

jobs:
  build:
    runs-on: ${{ inputs.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3.2.0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: vafanassieff
          password: ${{ secrets.CR_PAT }}

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Cache Docker layers
        uses: actions/cache@v3
        id: cache
        with:
          path: /tmp/.buildx-cache
          key: buildx-${{ github.sha }}
          restore-keys: |
            buildx-

      - name: Print Bake file
        env:
          COMMIT: ${{ inputs.commit }}
          IMAGE_PATH: ${{ inputs.path }}
        run: |
          docker buildx bake \
          --file ${{ inputs.path }}/image.hcl \
          --file docker-bake.hcl \
          --print ${{ inputs.target }}

      - name: Run Docker buildx without cache
        if: ${{ github.event.inputs.force }}
        env:
          COMMIT: ${{ inputs.commit }}
          IMAGE_PATH: ${{ inputs.path }}
          DOCKERFILE: ${{ inputs.dockerfile }}
        run: |
          docker buildx bake \
          --set *.output="type=registry" \
          --file ${{ inputs.path }}/image.hcl \
          --file docker-bake.hcl \
           ${{ inputs.target }}

      - name: Run Docker buildx against latest
        if: ${{ !github.event.inputs.force }}
        env:
          COMMIT: ${{ inputs.commit }}
          IMAGE_PATH: ${{ inputs.path }}
          DOCKERFILE: ${{ inputs.dockerfile }}
        run: |
          docker buildx bake \
          --set *.cache-from="type=local,src=/tmp/.buildx-cache" \
          --set *.cache-to="type=local,dest=/tmp/.buildx-cache" \
          --set *.output="type=registry" \
          --file ${{ inputs.path }}/image.hcl \
          --file docker-bake.hcl \
           ${{ inputs.target }}
