name: base-node

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - docker/base-node/**
      - scripts/**

jobs:
  build:
    uses: ./.github/workflows/bake.yml    
    permissions:
      contents: read
      packages: write
    secrets: inherit
    with:
      path: docker/base-node
      target: release
