name: base-alpine

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - docker/base-alpine/**
      - scripts/**

jobs:
  build:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/bake.yml
    secrets: inherit
    with:
      path: docker/base-alpine
      target: release
