name: bitcoin

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - docker/bitcoin/**

jobs:
  build:
    uses: ./.github/workflows/bake.yml
    secrets: inherit
    with:
      path: docker/bitcoin
      target: release
