name: bitcoin-regtest

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - docker/bitcoin-regtest/**

jobs:
  build:
    uses: ./.github/workflows/bake.yml
    secrets: inherit
    with:
      path: docker/bitcoin-regtest
      target: release
