name: bitcoin

on:
  workflow_dispatch:
    inputs:
      force:
        type: boolean
        description: Force build
        required: false
        default: false
  push:
    branches:
      - master
    paths:
      - docker/bitcoin/**

jobs:
  build:
    uses: ./.github/workflows/bake.yml    
    permissions:
      contents: read
      packages: write
    secrets: inherit
    with:
      path: docker/bitcoin
      target: release
