name: bitcoin-regtest

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - docker/bitcoin-regtest/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Build X
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: vafanassieff
          password: ${{ secrets.CR_PAT }}

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get bitcoin-regtest version
        run: echo 'BITCOIN_REGTEST_VERSION='$(grep -m 1 'ARG BITCOIN_REGTEST_VERSION=' docker/bitcoin-regtest/Dockerfile | cut -f2- -d=) >> $GITHUB_ENV

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/ln-markets/bitcoin-regtest
            lnmarkets/bitcoin-regtest
          tags: |
            type=raw,${{ env.BITCOIN_REGTEST_VERSION }}
            type=sha

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: docker/bitcoin-regtest
          platforms: linux/amd64,linux/arm64
          push: true
          cache-from: type=registry,ref=ghcr.io/ln-markets/bitcoin-regtest:latest
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
