name: debian

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - docker/debian/**
      - scripts/**

jobs:
  build:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/bake.yml
    secrets: inherit
    with:
      path: docker/debian
      target: release
