name: dogecoin

on:
  workflow_dispatch:
  push:
    branches:
      - "master"
    paths:
      - "dogecoin/**"

jobs:
  docker-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: vafanassieff
          password: ${{ secrets.CR_PAT }}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: vafanassieff
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get version
        run: |
          echo 'VERSION='$(grep -m 1 'ENV DOGECOIN_VERSION=' dogecoin/Dockerfile.ubuntu | cut -f2- -d=) >> $GITHUB_ENV

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: dogecoin
          file: dogecoin/Dockerfile.ubuntu
          push: true
          tags: |
            ghcr.io/vafanassieff/dogecoin:ubuntu-latest
            ghcr.io/vafanassieff/dogecoin:ubuntu-${{ env.VERSION }}
            vafanassieff/dogecoin:ubuntu-latest
            vafanassieff/dogecoin:ubuntu-${{ env.VERSION }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
