name: faraday

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - docker/faraday/**

jobs:
  build:
    uses: ./.github/workflows/bake.yml
    secrets: inherit
    with:
      path: docker/faraday
      target: release
