name: Baking factory

on:
  workflow_call:
    inputs:
      repo:
        description: "Git repository {owner}/{name}"
        required: true
        type: string
      branch:
        required: false
        type: string
        default: main
    outputs:
      COMMIT_SHA:
        description: "Checksum of the latest commit"
        value: ${{ jobs.latest-commit.outputs.COMMIT_SHA }}

jobs:
  latest-commit:
    runs-on: ubuntu-latest
    outputs:
      COMMIT_SHA: ${{ steps.commit.outputs.COMMIT_SHA }}
    steps:
      - name: Get latest commit shasum
        id: commit
        uses: sergeysova/jq-action@v2
        with:
          cmd: echo "COMMIT_SHA=$(curl -s https://api.github.com/repos/${{ inputs.repo }}/commits/${{ inputs.branch }} | jq -r .sha)" >> $GITHUB_OUTPUT

      - name: Print latest commit
        run: echo ${{ steps.commit.outputs.COMMIT_SHA }}
