name: lightning-terminal

on:
  workflow_dispatch:
    inputs:
      force:
        type: boolean
        description: Force build
        required: false
        default: false
  push:
    branches:
      - master
    paths:
      - docker/lightning-terminal/**

jobs:
  build:
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/bake.yml
    secrets: inherit
    with:
      path: docker/lightning-terminal
      target: release
