name: lightning-terminal

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - docker/lightning-terminal/**

jobs:
  build:
    uses: ./.github/workflows/bake.yml
    secrets: inherit
    with:
      path: docker/lightning-terminal
      target: release
