name: lnd-backup-channels

on:
  workflow_dispatch:
  push:
    branches:
      - "master"
    paths:
      - "lnd-backup-channels/**"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: vafanassieff
          password: ${{ secrets.CR_PAT }}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: vafanassieff
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: lnd-backup-channels
          push: true
          tags: |
            ghcr.io/vafanassieff/lnd-backup-channels:latest
            vafanassieff/lnd-backup-channels:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
