name: lndmon

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - docker/lndmon/**

jobs:
  build:
    uses: ./.github/workflows/bake.yml
    secrets: inherit
    with:
      path: docker/lndmon
      target: release
