name: lnp-node

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - docker/lnp-node/**

jobs:
  build:
    uses: ./.github/workflows/reusable-build.yml
    secrets: inherit
    with:
      path: docker/lnp-node
      target: release
