name: loop

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - docker/loop/**

jobs:
  build:
    uses: ./.github/workflows/bake.yml
    secrets: inherit
    with:
      path: docker/loop
      target: release
