name: nostr-rs-relay

on:
  workflow_dispatch:
    inputs:
      force:
        type: boolean
        description: Force build
        required: false
        default: false
  push:
    branches:
      - master
    paths:
      - docker/nostr-rs-relay/**

jobs:
  build:
    uses: ./.github/workflows/bake.yml    
    permissions:
      contents: read
      packages: write
    secrets: inherit
    with:
      runs-on: self-hosted
      path: docker/nostr-rs-relay
      target: release
