name: pool

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - docker/pool/**

jobs:
  build:
    uses: ./.github/workflows/bake.yml
    secrets: inherit
    with:
      path: docker/pool
      target: release
