name: taro-latest

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8,20 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Build X
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: vafanassieff
          password: ${{ secrets.CR_PAT }}

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get latest taro commit sha
        uses: sergeysova/jq-action@v2
        with:
          cmd: echo 'TARO_COMMIT='$(curl -s https://api.github.com/repos/lightninglabs/taro/commits/main | jq -r .sha) >> $GITHUB_ENV

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/ln-markets/taro
            lnmarkets/taro
          tags: |
            type=raw,latest
            type=raw,commit-${{ env.TARO_COMMIT }}
            type=sha

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: .
          file: docker/taro/Dockerfile
          platforms: linux/amd64,linux/arm64
          build-args: TARO_COMMIT=${{ env.TARO_COMMIT }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
