name: taro-latest

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8,20 * * *"

jobs:
  latest:
    uses: ./.github/workflows/latest-commit.yml
    with:
      repo: lightninglabs/taro
      branch: main

  build:
    needs: latest
    uses: ./.github/workflows/bake.yml
    secrets: inherit
    with:
      path: docker/taro
      target: nightly
      commit: ${{ needs.latest.outputs.COMMIT_SHA }}