name: tor

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - docker/tor/**

jobs:
  build:
    uses: ./.github/workflows/bake.yml
    secrets: inherit
    with:
      path: docker/tor
      target: release
